import { Emoji } from "@/interfaces/emoji.interface";

export const emojisData: Emoji[] = [
  {
    code: "1F600",
    emoji: "😀",
    name: "grinning face",
    category: "Smileys & Emotion (face-smiling)",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    code: "1F603",
    emoji: "😃",
    name: "grinning face with big eyes",
    category: "Smileys & Emotion (face-smiling)",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    code: "1F604",
    emoji: "😄",
    name: "grinning face with smiling eyes",
    category: "Smileys & Emotion (face-smiling)",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    code: "1F601",
    emoji: "😁",
    name: "beaming face with smiling eyes",
    category: "Smileys & Emotion (face-smiling)",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    code: "1F606",
    emoji: "😆",
    name: "grinning squinting face",
    category: "Smileys & Emotion (face-smiling)",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    code: "1F605",
    emoji: "😅",
    name: "grinning face with sweat",
    category: "Smileys & Emotion (face-smiling)",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    code: "1F923",
    emoji: "🤣",
    name: "rolling on the floor laughing",
    category: "Smileys & Emotion (face-smiling)",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    code: "1F602",
    emoji: "😂",
    name: "face with tears of joy",
    category: "Smileys & Emotion (face-smiling)",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    code: "1F642",
    emoji: "🙂",
    name: "slightly smiling face",
    category: "Smileys & Emotion (face-smiling)",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    code: "1F643",
    emoji: "🙃",
    name: "upside-down face",
    category: "Smileys & Emotion (face-smiling)",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    code: "1F609",
    emoji: "😉",
    name: "winking face",
    category: "Smileys & Emotion (face-smiling)",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    code: "1F60A",
    emoji: "😊",
    name: "smiling face with smiling eyes",
    category: "Smileys & Emotion (face-smiling)",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    code: "1F607",
    emoji: "😇",
    name: "smiling face with halo",
    category: "Smileys & Emotion (face-smiling)",
    group: "Smileys & Emotion",
    subgroup: "face-smiling",
  },
  {
    code: "1F970",
    emoji: "🥰",
    name: "smiling face with hearts",
    category: "Smileys & Emotion (face-affection)",
    group: "Smileys & Emotion",
    subgroup: "face-affection",
  },
  {
    code: "1F60D",
    emoji: "😍",
    name: "smiling face with heart-eyes",
    category: "Smileys & Emotion (face-affection)",
    group: "Smileys & Emotion",
    subgroup: "face-affection",
  },
  {
    code: "1F929",
    emoji: "🤩",
    name: "star-struck",
    category: "Smileys & Emotion (face-affection)",
    group: "Smileys & Emotion",
    subgroup: "face-affection",
  },
  {
    code: "1F618",
    emoji: "😘",
    name: "face blowing a kiss",
    category: "Smileys & Emotion (face-affection)",
    group: "Smileys & Emotion",
    subgroup: "face-affection",
  },
  {
    code: "1F617",
    emoji: "😗",
    name: "kissing face",
    category: "Smileys & Emotion (face-affection)",
    group: "Smileys & Emotion",
    subgroup: "face-affection",
  },
  {
    code: "263A FE0F",
    emoji: "🙂",
    name: "smiling face",
    category: "Smileys & Emotion (face-affection)",
    group: "Smileys & Emotion",
    subgroup: "face-affection",
  },
  {
    code: "1F61A",
    emoji: "😚",
    name: "kissing face with closed eyes",
    category: "Smileys & Emotion (face-affection)",
    group: "Smileys & Emotion",
    subgroup: "face-affection",
  },
  {
    code: "1F619",
    emoji: "😙",
    name: "kissing face with smiling eyes",
    category: "Smileys & Emotion (face-affection)",
    group: "Smileys & Emotion",
    subgroup: "face-affection",
  },
  {
    code: "1F972",
    emoji: "🥲",
    name: "smiling face with tear",
    category: "Smileys & Emotion (face-affection)",
    group: "Smileys & Emotion",
    subgroup: "face-affection",
  },
  {
    code: "1F60B",
    emoji: "😋",
    name: "face savoring food",
    category: "Smileys & Emotion (face-tongue)",
    group: "Smileys & Emotion",
    subgroup: "face-tongue",
  },
  {
    code: "1F61B",
    emoji: "😛",
    name: "face with tongue",
    category: "Smileys & Emotion (face-tongue)",
    group: "Smileys & Emotion",
    subgroup: "face-tongue",
  },
  {
    code: "1F61C",
    emoji: "😜",
    name: "winking face with tongue",
    category: "Smileys & Emotion (face-tongue)",
    group: "Smileys & Emotion",
    subgroup: "face-tongue",
  },
  {
    code: "1F92A",
    emoji: "🤪",
    name: "zany face",
    category: "Smileys & Emotion (face-tongue)",
    group: "Smileys & Emotion",
    subgroup: "face-tongue",
  },
  {
    code: "1F61D",
    emoji: "😝",
    name: "squinting face with tongue",
    category: "Smileys & Emotion (face-tongue)",
    group: "Smileys & Emotion",
    subgroup: "face-tongue",
  },
  {
    code: "1F911",
    emoji: "🤑",
    name: "money-mouth face",
    category: "Smileys & Emotion (face-tongue)",
    group: "Smileys & Emotion",
    subgroup: "face-tongue",
  },
  {
    code: "1F917",
    emoji: "🤗",
    name: "hugging face",
    category: "Smileys & Emotion (face-hand)",
    group: "Smileys & Emotion",
    subgroup: "face-hand",
  },
  {
    code: "1F92D",
    emoji: "🤭",
    name: "face with hand over mouth",
    category: "Smileys & Emotion (face-hand)",
    group: "Smileys & Emotion",
    subgroup: "face-hand",
  },
  {
    code: "1F92B",
    emoji: "🤫",
    name: "shushing face",
    category: "Smileys & Emotion (face-hand)",
    group: "Smileys & Emotion",
    subgroup: "face-hand",
  },
  {
    code: "1F914",
    emoji: "🤔",
    name: "thinking face",
    category: "Smileys & Emotion (face-hand)",
    group: "Smileys & Emotion",
    subgroup: "face-hand",
  },
  {
    code: "1F910",
    emoji: "🤐",
    name: "zipper-mouth face",
    category: "Smileys & Emotion (face-neutral-skeptical)",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    code: "1F928",
    emoji: "🤨",
    name: "face with raised eyebrow",
    category: "Smileys & Emotion (face-neutral-skeptical)",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    code: "1F610",
    emoji: "😐",
    name: "neutral face",
    category: "Smileys & Emotion (face-neutral-skeptical)",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    code: "1F611",
    emoji: "😑",
    name: "expressionless face",
    category: "Smileys & Emotion (face-neutral-skeptical)",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    code: "1F636",
    emoji: "😶",
    name: "face without mouth",
    category: "Smileys & Emotion (face-neutral-skeptical)",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    code: "1F636 200D 1F32B FE0F",
    emoji: "😶‍🌫️",
    name: "face in clouds",
    category: "Smileys & Emotion (face-neutral-skeptical)",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    code: "1F636 200D 1F32B",
    emoji: "😶‍🌫",
    name: "face in clouds",
    category: "Smileys & Emotion (face-neutral-skeptical)",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    code: "1F60F",
    emoji: "😏",
    name: "smirking face",
    category: "Smileys & Emotion (face-neutral-skeptical)",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    code: "1F612",
    emoji: "😒",
    name: "unamused face",
    category: "Smileys & Emotion (face-neutral-skeptical)",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    code: "1F644",
    emoji: "🙄",
    name: "face with rolling eyes",
    category: "Smileys & Emotion (face-neutral-skeptical)",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    code: "1F62C",
    emoji: "😬",
    name: "grimacing face",
    category: "Smileys & Emotion (face-neutral-skeptical)",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    code: "1F62E 200D 1F4A8",
    emoji: "😮‍💨",
    name: "face exhaling",
    category: "Smileys & Emotion (face-neutral-skeptical)",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    code: "1F925",
    emoji: "🤥",
    name: "lying face",
    category: "Smileys & Emotion (face-neutral-skeptical)",
    group: "Smileys & Emotion",
    subgroup: "face-neutral-skeptical",
  },
  {
    code: "1F60C",
    emoji: "😌",
    name: "relieved face",
    category: "Smileys & Emotion (face-sleepy)",
    group: "Smileys & Emotion",
    subgroup: "face-sleepy",
  },
];
